phudb/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
}
);

Route::get('hello-world', 'HelloWorldController@show');
Route::resource('users', 'UsersController');

phudb/app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class User extends Model
{
    protected $fillable = [
        'mail_address', 'password', 'name', 'address', 'phone',
    ];

    public function getUsers ()
    {
        return User::orderBy('mail_address', 'ASC')->paginate(20);
    }

    public function addUsers($data)
    {
    	$data['password'] = bcrypt($data['password']);
        return User::create($data);
    }

    public function findUsers($data)
    {

        return User::where('mail_address', 'like', '%'.$data['email'].'%')
        ->where('name', 'like', '%'.$data['name'].'%')
        ->where('address', 'like', '%'.$data['address'].'%')
        ->where('phone', $data['phone'])
        ->paginate(20);
    }

}

phudb/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

phudb/app/Http/Controllers/HelloWorldController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HelloWorldController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        return view('hello_world.show');
    }
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function show($id)
    // {
    //     //
    // }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

phudb/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Hash;
use DB;


class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $modelUsers;

    public function __construct(User $users)
    {
        $this->modelUsers = $users;
    }

    public function index(Request $req)
    {
        $users = $this->modelUsers->getUsers();
        if ($req->all()) {
           $users = $this->modelUsers->findUsers($req->all());
        }
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $users = $request->all();
        $users = $this->modelUsers->addUsers($users);
        $request->session()->flash('status', 'Thêm user thành công');
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

}

phudb/resources/views/hello_world/show.blade.php
Hello

phudb/resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>
<head>
    @include('layouts.head')
</head>
<body>
    @include('layouts.header')
    @yield('content')
    @include('layouts.footer')
</body>
</html>

phudb/resources/views/layouts/footer.blade.php
<footer>
    <h1 style="text-align: center;">PHP training by LIFETIME technologies</h1>
</footer>

phudb/resources/views/layouts/head.blade.php
<meta charset="UTF-8">
<title>@yield('title')</title> 
<link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
<style type="text/css">
        .error1{
            color: red;
        }
        .error2{
            border:solid 1px red;
        }
        
    </style>
</style>

phudb/resources/views/layouts/header.blade.php
<header>
    <h1 style="text-align: center;">@yield('title')</h1>
</header>

phudb/resources/views/users/create.blade.php
@extends('layouts.default')
@section('title', __('Thêm mới người dùng'))
@section('content')
<body>
    <form action="{{ route('users.store') }}" method="POST" >
    <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
        <div class="container">
            <div class="row">
                <div class="input-group col-md-6 offset-md-5" style="margin-top: 10px">
                    <h3>Thêm mới</h3>
                </div>
            </div>
            <div class="row">
                <div class="input-group col-md-6 offset-md-4" style="">
                    <table>
                        <tr>
                            <td class="@if ($errors->has('mail_address')) {{'error1'}} @endif">Địa chỉ email</td>
                            <td><input type="text" class="form-control @if ($errors->has('mail_address')) {{'error2'}} @endif" name="mail_address"></td>
                        </tr>
                        <tr>
                            <td colspan="2" class="error1">
                                {{ $errors->first('mail_address') }}
                            </td>
                        </tr>

                        <tr>
                            <td class="@if ($errors->has('password')) {{'error1'}} @endif">Mật khẩu</td>
                            <td><input type="password" class="form-control @if ($errors->has('password')) {{'error2'}} @endif" name="password"></td>
                        </tr>

                        <tr>
                            <td colspan="2" class="error1">
                                {{ $errors->first('password') }}
                            </td>
                        </tr>

                        <tr>
                            <td class="@if ($errors->has('password_confirmation')) {{'error1'}} @endif">Mật khẩu xác nhận</td>
                            <td><input type="password" class="form-control @if ($errors->has('password_confirmation')) {{'error2'}} @endif" name="password_confirmation"></td>
                        </tr>

                        <tr>
                            <td colspan="2" class="error1">
                                {{ $errors->first('password_confirmation') }}
                            </td>
                        </tr>

                        <tr>
                            <td class="@if ($errors->has('name')) {{'error1'}} @endif">Tên</td>
                            <td><input type="text" class="form-control @if ($errors->has('name')) {{'error2'}} @endif" name="name"></td>
                        </tr>

                        <tr>
                            <td colspan="2" class="error1">
                                {{ $errors->first('name') }}
                            </td>
                        </tr>

                        <tr>
                            <td class="@if ($errors->has('address')) {{'error1'}} @endif">Địa chỉ</td>
                            <td><input type="text" class="form-control @if ($errors->has('address')) {{'error2'}} @endif" name="address"></td>
                        </tr>

                        <tr>
                            <td colspan="2" class="error1">
                                {{ $errors->first('address') }}
                            </td>
                        </tr>

                        <tr>
                            <td class="@if ($errors->has('phone')) {{'error1'}} @endif">Số điện thoại</td>
                            <td><input type="text" class="form-control @if ($errors->has('phone')) {{'error2'}} @endif" name="phone"></td>
                        </tr>

                        <tr>
                            <td colspan="2" class="error1">
                                {{ $errors->first('phone') }}
                            </td>
                        </tr>
                        
                        <tr>
                            <td></td>
                            <td><button type="submit" href="{{ url('users/') }}" name="create_action" class="btn btn-primary" style="width: 100%">Register</button></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </form>
@endsection

phudb/resources/views/users/index.blade.php
@extends('layouts.default')
@section('title', __('Danh sách người dùng'))
@section('content')

<body>
    <form method="GET" action="{{ route('users.index') }}">
        <label>Địa chỉ email</label><input type="text" name="email" value="">
        <label>Tên</label><input type="text" name="name" value="">
        <label>Địa chỉ</label><input type="text" name="address" value="">
        <label>Số điện thoại</label><input type="text" name="phone" value=""><button type="submit">Tìm kiếm</button>
    </form>
    <div class="container">
            @if (session('status'))
                <div class="alert alert-info">{{session('status')}}</div>
            @endif
        <table class="table table-bordered" style="margin-top: 20px">
            <thead style="text-align: center">
                <tr>
                    <th>STT</th>
                    <th>Địa chỉ email</th>
                    <th>Tên</th>
                    <th>Địa chỉ</th>
                    <th>Số điện thoại</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = ($users->currentpage()-1)*$users->perpage() +1; ?>
                @foreach($users as $user)
                    <tr>
                        <th>{{ $i++ }}</th>
                        <th>{{ $user-> mail_address }}</th>
                        <th>{{ Helper::toUpperCase($user->name) }}</th>
                        <th>{{ $user-> address }}</th>
                        <th>{{ $user-> phone }}</th>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{ $users->links() }}
        <a href="{{ route('users.create') }}" class="button">Thêm mới User</a>
    </div>
@endsection